# Generated by Django 4.2.7 on 2023-11-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizWise', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_examinee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_examiner',
            field=models.BooleanField(default=False),
        ),
    ]
